#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CELL_SIZE 4
#define SCREEN_WIDTH 540
#define SCREEN_HEIGHT 960
#define GRID_WIDTH (SCREEN_WIDTH / CELL_SIZE)
#define GRID_HEIGHT (SCREEN_HEIGHT / CELL_SIZE)

#endif // CONSTANTS_H