#ifndef CONSTANTS_H
#define CONSTANTS_H

#define CELL_SIZE 4
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define GRID_WIDTH (SCREEN_WIDTH / CELL_SIZE)
#define GRID_HEIGHT (SCREEN_HEIGHT / CELL_SIZE)

#endif // CONSTANTS_H